### ISSUE TITLE
[OL] [Implementierung] Map

### ISSUE THREAD

**Issue by AxxL** [mapbender/mapbender#689]
- [x] Initialize with configured sources and layers
- [x] [Initialize with configured starting srs](https://github.com/mapbender/mapbender/issues/949)
- [x] Initialize with configured startExtent
   - [x] [use Map-configured startExtent if no POI](https://github.com/mapbender/mapbender/issues/949)
   - [x] start at POI if single POI given in URL
- [x] [Initialize with configured maxExtent](https://github.com/mapbender/mapbender/issues/949)
- [x] Restrict to configured zoom levels
- [ ] [Find solution for dynamic SRS switching on WMS1.3.0 between changeAxis on / off](https://github.com/mapbender/mapbender/issues/963)
- [ ] [Respect configured tileSize for WMS with option 'tiled'=true](https://github.com/mapbender/mapbender/issues/971) (currently uses OL4 default 256x256)

**Comment by werrolf** [comment]
POI URL evaluation (plus collaterally discovered 'center' URL parameter) evaluation has been implemented.

**Comment by AxxL** [comment]
Tickets erstellt. Ich schließe hier.
